### ISSUE TITLE
Any $ sympols need to be escaped with a $ symbol.

### ISSUE THREAD

**Issue by redRolf** [sapk/docker-volume-rclone#5]
This is regarding the Docker Compose section in the readme.
current state:
```
    cloud_storage_data:
      driver: sapk/plugin-rclone
      driver_opts:
        config: "$(base64 ~/.config/rclone/rclone.conf)"
        args: "--read-only --fast-list"
        remote: "https://sos-ch-dk-2.exo.io:rmcsearchresiliotestrz"
```
according to: https://github.com/moby/moby/issues/30629
this is how it should look.

```
    cloud_storage_data:
      driver: sapk/plugin-rclone
      driver_opts:
        config: "$$(base64 ~/.config/rclone/rclone.conf)"
        args: "--read-only --fast-list"
        remote: "https://sos-ch-dk-2.exo.io:rmcsearchresiliotestrz"
```

After using two $ signs my docker compose file worked. Before that I got the error:
`Invalid interpolation format for "driver_opts`

**Comment by redRolf** [comment]
Sorry my fault. The config needs to be converted to base 64 and then pasted in at config: "base64 string of rclone.conf"

**Comment by sapk** [comment]
No problems this part isn't clear enough maybe I should add step for generating the base64 in global var and use it via variable substitution.

**Comment by redRolf** [comment]
thats what I have done now :)
```
      driver_opts:
        config: ${RCLONE_CONF_BASE64}
        args: "--read-only --fast-list"
        remote: "exoscale-encrypted:${S3_BUCKET}"
```
