### ISSUE TITLE
Permissions workaround for postgres

### ISSUE THREAD

**Issue by YiannisGkoufas** [sapk/docker-volume-rclone#53]
Hi there,

thanks for the extremely useful plugin. I am trying to use a volume created by the plugin in docker-compose with postgres:
```
version: '3'

services:
  db:
    user: "postgres:postgres"
    image: postgres:13-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # Un-comment to access the db service directly
#   ports:
#     - 5432:5432
    networks:
      - db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
```
When it tries to write some data I get:
```
mkdir: can't create directory '/var/lib/postgresql/data/': Permission denied
```
My guess is that it has to do with the chown that postgres container is doing. Is there a way to work-around this?

Thanks!
