### ISSUE TITLE
Sonarr

### ISSUE THREAD

**Issue by StefanFransen** [sapk/docker-volume-rclone#9]
Hey,

I have been using your plugin since a few days in combination with Sonarr, Docker Compose and a encrypted GDrive and it works fine so far.
Files get moved after downloading to the volume and then get uploaded to GDrive.

When a file gets moved to the volume a partial file is first created which is then edited and renamed.
I was wondering if it is more efficient to filter out those partial files. So only video files etc gets uploaded.

Rclone has argruments to filter uploads, but does this plugin actually supports this?

Anyway thanks for the work you've done so far, even though this plugin is still WIP it works!

Stefan Fransen.

**Comment by sapk** [comment]
Hi, and at first thanks.

I use it for nearly the same reason. My setup use the rclone cache volume overlay to hold off temporary file and will upload file after few hour/minutes if they exist. It offer a better compatibility as a normal fs. 
Otherwise any option that could fit in the rclone.conf file will be compatible.

If you want I can provide an example based on my rclone.conf setup.

I am stil considering this wip as it would silently fail when rclone close due to an error (network, memory,...). But that also a l'imitation of docker. I use an healthchek command that monitor the FS to know if the folder is ready or not to mitigate this case.

**Comment by StefanFransen** [comment]
Yes please, the cache sounds like a great idea.

Is the healthcheck already implemented in the plugin, or does this require extra configuration?

**Comment by sapk** [comment]
@StefanFransen The healthchek is at the container/image level. You can configure it in the Dockerfile or in the docker-compose.yml. I will send the config when I have access to my computer.

**Comment by StefanFransen** [comment]
Can you share your healthcheck fot the docker-compose.yml file aswell?

Thanks.

**Comment by sapk** [comment]
For the heathcheck in docker-compose :
```
version: '3.6' 
  services:                                                                          
    app:                                                        
       image: soe/img
       healthcheck:    
           test: ls /volumes/subfolder || exit 1 
           interval: 1m
           timeout: 15s 
           retries: 3                                              
           start_period: 15s
```
